name:                peng
version:             0.1.0.0
github:              "sedwards-lab/peng"
license:             BSD3
author:              "Stephen A. Edwards"
maintainer:          "sedwards@cs.columbia.edu"
copyright:           "2020 Stephen A. Edwards"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Real-time programming language
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sedwards-lab/peng#README>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  dependencies:
  - prettyprinter >= 1.7.0
  - array

executables:
  peng-exe:
    main:                Main.hs
    source-dirs:         app

    ghc-options:
    - -Wall
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N

    dependencies:
    - peng

    build-tools:
    - happy
    - alex

tests:
  scanner-test:
    main:		test/ScannerTest.hs
#    source-dirs:	test
    dependencies:
    - peng

  parser-test:
    main:		test/ParserTest.hs
#    source-dirs:	test
    dependencies:
    - peng